# -*- coding: utf-8 -*-
"""perceptron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EhzH7igWTEjWBU6dqHYrdo8GAc9LcmN8
"""

import numpy as np

w = [0.4,-0.6,0.6,0.5]
x = [0,0,1,-1]
y=0
n = 0.4

u = x[0]*w[0] +  x[1]*w[1] + x[2]*w[2] -1*w[3]
print(u)

if(u>0):
  y=1
else:
  y=-1
print(y)

for i in range(4):
  w[i] = w[i] +  n*x[i]*(-1-y)
  print(x[i])
print(w, "depois")

x = [1,1,0,-1]
u = x[0]*w[0] +  x[1]*w[1] + x[2]*w[2] -1*w[3]
print(u)

if(u>0):
  y=1
else:
  y=-1
print(y)

for i in range(4):
  w[i] = w[i] +  n*x[i]*(1-y)
  print(x[i])
print(w, "depois")

x = [0,0,1,-1]
u = x[0]*w[0] +  x[1]*w[1] + x[2]*w[2] -1*w[3]
print(u)

if(u>0):
  y=1
else:
  y=-1
print(y)

for i in range(4):
  w[i] = w[i] +  n*x[i]*(-1-y)
  print(x[i])
print(w, "depois")

x = [1,1,0,-1]
u = x[0]*w[0] +  x[1]*w[1] + x[2]*w[2] -1*w[3]
print(u)

if(u>0):
  y=1
else:
  y=-1
print(y)

for i in range(4):
  w[i] = w[i] +  n*x[i]*(1-y)
  print(x[i])
print(w, "depois")

x = [1,1,1,-1]
u = x[0]*w[0] +  x[1]*w[1] + x[2]*w[2] -1*w[3]
print(u)

if(u>0):
  y=1
else:
  y=-1
print(y)

x = [0,0,0,-1]
u = x[0]*w[0] +  x[1]*w[1] + x[2]*w[2] -1*w[3]
print(u)

if(u>0):
  y=1
else:
  y=-1
print(y)

x = [1,0,0,-1]
u = x[0]*w[0] +  x[1]*w[1] + x[2]*w[2] -1*w[3]
print(u)

if(u>0):
  y=1
else:
  y=-1
print(y)

x = [0,1,1,-1]
u = x[0]*w[0] +  x[1]*w[1] + x[2]*w[2] -1*w[3]
print(u)

if(u>0):
  y=1
else:
  y=-1
print(y)